### ISSUE TITLE
cstor-pool container unable to start due to libjson-c.so.2:

### ISSUE THREAD

**Issue by xUnholy** [openebs/vsm-image#3]
I got some strange errors about the libjson library.

Running the following command: `k logs cstor-pool-kzh3-586f7ccbb9-qghpn cstor-pool`

```
/usr/local/bin/zrepl: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory
```

**Comment by kmova** [comment]
Tracked under: 

https://github.com/openebs/openebs/issues/3037
